# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/media/sylvus/4AA492E1A492CF37/Users/Sylvus/ETHZ/FS15/Fast Numerical Code/Project/libDAI"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/media/sylvus/4AA492E1A492CF37/Users/Sylvus/ETHZ/FS15/Fast Numerical Code/Project/libDAI"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\" \"main\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/media/sylvus/4AA492E1A492CF37/Users/Sylvus/ETHZ/FS15/Fast Numerical Code/Project/libDAI/CMakeFiles" "/media/sylvus/4AA492E1A492CF37/Users/Sylvus/ETHZ/FS15/Fast Numerical Code/Project/libDAI/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/media/sylvus/4AA492E1A492CF37/Users/Sylvus/ETHZ/FS15/Fast Numerical Code/Project/libDAI/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named dai

# Build rule for target.
dai: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dai
.PHONY : dai

# fast build rule for target.
dai/fast:
	$(MAKE) -f src/CMakeFiles/dai.dir/build.make src/CMakeFiles/dai.dir/build
.PHONY : dai/fast

#=============================================================================
# Target rules for targets named testbbp

# Build rule for target.
testbbp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testbbp
.PHONY : testbbp

# fast build rule for target.
testbbp/fast:
	$(MAKE) -f tests/CMakeFiles/testbbp.dir/build.make tests/CMakeFiles/testbbp.dir/build
.PHONY : testbbp/fast

#=============================================================================
# Target rules for targets named testdai

# Build rule for target.
testdai: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testdai
.PHONY : testdai

# fast build rule for target.
testdai/fast:
	$(MAKE) -f tests/CMakeFiles/testdai.dir/build.make tests/CMakeFiles/testdai.dir/build
.PHONY : testdai/fast

#=============================================================================
# Target rules for targets named testem

# Build rule for target.
testem: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testem
.PHONY : testem

# fast build rule for target.
testem/fast:
	$(MAKE) -f tests/CMakeFiles/testem.dir/build.make tests/CMakeFiles/testem.dir/build
.PHONY : testem/fast

#=============================================================================
# Target rules for targets named alldai_test

# Build rule for target.
alldai_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 alldai_test
.PHONY : alldai_test

# fast build rule for target.
alldai_test/fast:
	$(MAKE) -f tests/unit/CMakeFiles/alldai_test.dir/build.make tests/unit/CMakeFiles/alldai_test.dir/build
.PHONY : alldai_test/fast

#=============================================================================
# Target rules for targets named bipgraph_test

# Build rule for target.
bipgraph_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bipgraph_test
.PHONY : bipgraph_test

# fast build rule for target.
bipgraph_test/fast:
	$(MAKE) -f tests/unit/CMakeFiles/bipgraph_test.dir/build.make tests/unit/CMakeFiles/bipgraph_test.dir/build
.PHONY : bipgraph_test/fast

#=============================================================================
# Target rules for targets named clustergraph_test

# Build rule for target.
clustergraph_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clustergraph_test
.PHONY : clustergraph_test

# fast build rule for target.
clustergraph_test/fast:
	$(MAKE) -f tests/unit/CMakeFiles/clustergraph_test.dir/build.make tests/unit/CMakeFiles/clustergraph_test.dir/build
.PHONY : clustergraph_test/fast

#=============================================================================
# Target rules for targets named dag_test

# Build rule for target.
dag_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dag_test
.PHONY : dag_test

# fast build rule for target.
dag_test/fast:
	$(MAKE) -f tests/unit/CMakeFiles/dag_test.dir/build.make tests/unit/CMakeFiles/dag_test.dir/build
.PHONY : dag_test/fast

#=============================================================================
# Target rules for targets named daialg_test

# Build rule for target.
daialg_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 daialg_test
.PHONY : daialg_test

# fast build rule for target.
daialg_test/fast:
	$(MAKE) -f tests/unit/CMakeFiles/daialg_test.dir/build.make tests/unit/CMakeFiles/daialg_test.dir/build
.PHONY : daialg_test/fast

#=============================================================================
# Target rules for targets named enum_test

# Build rule for target.
enum_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 enum_test
.PHONY : enum_test

# fast build rule for target.
enum_test/fast:
	$(MAKE) -f tests/unit/CMakeFiles/enum_test.dir/build.make tests/unit/CMakeFiles/enum_test.dir/build
.PHONY : enum_test/fast

#=============================================================================
# Target rules for targets named exceptions_test

# Build rule for target.
exceptions_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 exceptions_test
.PHONY : exceptions_test

# fast build rule for target.
exceptions_test/fast:
	$(MAKE) -f tests/unit/CMakeFiles/exceptions_test.dir/build.make tests/unit/CMakeFiles/exceptions_test.dir/build
.PHONY : exceptions_test/fast

#=============================================================================
# Target rules for targets named factor_test

# Build rule for target.
factor_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 factor_test
.PHONY : factor_test

# fast build rule for target.
factor_test/fast:
	$(MAKE) -f tests/unit/CMakeFiles/factor_test.dir/build.make tests/unit/CMakeFiles/factor_test.dir/build
.PHONY : factor_test/fast

#=============================================================================
# Target rules for targets named factorgraph_test

# Build rule for target.
factorgraph_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 factorgraph_test
.PHONY : factorgraph_test

# fast build rule for target.
factorgraph_test/fast:
	$(MAKE) -f tests/unit/CMakeFiles/factorgraph_test.dir/build.make tests/unit/CMakeFiles/factorgraph_test.dir/build
.PHONY : factorgraph_test/fast

#=============================================================================
# Target rules for targets named graph_test

# Build rule for target.
graph_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 graph_test
.PHONY : graph_test

# fast build rule for target.
graph_test/fast:
	$(MAKE) -f tests/unit/CMakeFiles/graph_test.dir/build.make tests/unit/CMakeFiles/graph_test.dir/build
.PHONY : graph_test/fast

#=============================================================================
# Target rules for targets named index_test

# Build rule for target.
index_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 index_test
.PHONY : index_test

# fast build rule for target.
index_test/fast:
	$(MAKE) -f tests/unit/CMakeFiles/index_test.dir/build.make tests/unit/CMakeFiles/index_test.dir/build
.PHONY : index_test/fast

#=============================================================================
# Target rules for targets named prob_test

# Build rule for target.
prob_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 prob_test
.PHONY : prob_test

# fast build rule for target.
prob_test/fast:
	$(MAKE) -f tests/unit/CMakeFiles/prob_test.dir/build.make tests/unit/CMakeFiles/prob_test.dir/build
.PHONY : prob_test/fast

#=============================================================================
# Target rules for targets named properties_test

# Build rule for target.
properties_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 properties_test
.PHONY : properties_test

# fast build rule for target.
properties_test/fast:
	$(MAKE) -f tests/unit/CMakeFiles/properties_test.dir/build.make tests/unit/CMakeFiles/properties_test.dir/build
.PHONY : properties_test/fast

#=============================================================================
# Target rules for targets named regiongraph_test

# Build rule for target.
regiongraph_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 regiongraph_test
.PHONY : regiongraph_test

# fast build rule for target.
regiongraph_test/fast:
	$(MAKE) -f tests/unit/CMakeFiles/regiongraph_test.dir/build.make tests/unit/CMakeFiles/regiongraph_test.dir/build
.PHONY : regiongraph_test/fast

#=============================================================================
# Target rules for targets named smallset_test

# Build rule for target.
smallset_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 smallset_test
.PHONY : smallset_test

# fast build rule for target.
smallset_test/fast:
	$(MAKE) -f tests/unit/CMakeFiles/smallset_test.dir/build.make tests/unit/CMakeFiles/smallset_test.dir/build
.PHONY : smallset_test/fast

#=============================================================================
# Target rules for targets named util_test

# Build rule for target.
util_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 util_test
.PHONY : util_test

# fast build rule for target.
util_test/fast:
	$(MAKE) -f tests/unit/CMakeFiles/util_test.dir/build.make tests/unit/CMakeFiles/util_test.dir/build
.PHONY : util_test/fast

#=============================================================================
# Target rules for targets named var_test

# Build rule for target.
var_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 var_test
.PHONY : var_test

# fast build rule for target.
var_test/fast:
	$(MAKE) -f tests/unit/CMakeFiles/var_test.dir/build.make tests/unit/CMakeFiles/var_test.dir/build
.PHONY : var_test/fast

#=============================================================================
# Target rules for targets named varset_test

# Build rule for target.
varset_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 varset_test
.PHONY : varset_test

# fast build rule for target.
varset_test/fast:
	$(MAKE) -f tests/unit/CMakeFiles/varset_test.dir/build.make tests/unit/CMakeFiles/varset_test.dir/build
.PHONY : varset_test/fast

#=============================================================================
# Target rules for targets named weightedgraph_test

# Build rule for target.
weightedgraph_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 weightedgraph_test
.PHONY : weightedgraph_test

# fast build rule for target.
weightedgraph_test/fast:
	$(MAKE) -f tests/unit/CMakeFiles/weightedgraph_test.dir/build.make tests/unit/CMakeFiles/weightedgraph_test.dir/build
.PHONY : weightedgraph_test/fast

#=============================================================================
# Target rules for targets named createfg

# Build rule for target.
createfg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 createfg
.PHONY : createfg

# fast build rule for target.
createfg/fast:
	$(MAKE) -f utils/CMakeFiles/createfg.dir/build.make utils/CMakeFiles/createfg.dir/build
.PHONY : createfg/fast

#=============================================================================
# Target rules for targets named fg2dot

# Build rule for target.
fg2dot: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fg2dot
.PHONY : fg2dot

# fast build rule for target.
fg2dot/fast:
	$(MAKE) -f utils/CMakeFiles/fg2dot.dir/build.make utils/CMakeFiles/fg2dot.dir/build
.PHONY : fg2dot/fast

#=============================================================================
# Target rules for targets named fginfo

# Build rule for target.
fginfo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fginfo
.PHONY : fginfo

# fast build rule for target.
fginfo/fast:
	$(MAKE) -f utils/CMakeFiles/fginfo.dir/build.make utils/CMakeFiles/fginfo.dir/build
.PHONY : fginfo/fast

#=============================================================================
# Target rules for targets named uai2fg

# Build rule for target.
uai2fg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uai2fg
.PHONY : uai2fg

# fast build rule for target.
uai2fg/fast:
	$(MAKE) -f utils/CMakeFiles/uai2fg.dir/build.make utils/CMakeFiles/uai2fg.dir/build
.PHONY : uai2fg/fast

#=============================================================================
# Target rules for targets named example

# Build rule for target.
example: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example
.PHONY : example

# fast build rule for target.
example/fast:
	$(MAKE) -f examples/CMakeFiles/example.dir/build.make examples/CMakeFiles/example.dir/build
.PHONY : example/fast

#=============================================================================
# Target rules for targets named example_bipgraph

# Build rule for target.
example_bipgraph: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example_bipgraph
.PHONY : example_bipgraph

# fast build rule for target.
example_bipgraph/fast:
	$(MAKE) -f examples/CMakeFiles/example_bipgraph.dir/build.make examples/CMakeFiles/example_bipgraph.dir/build
.PHONY : example_bipgraph/fast

#=============================================================================
# Target rules for targets named example_imagesegmentation

# Build rule for target.
example_imagesegmentation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example_imagesegmentation
.PHONY : example_imagesegmentation

# fast build rule for target.
example_imagesegmentation/fast:
	$(MAKE) -f examples/CMakeFiles/example_imagesegmentation.dir/build.make examples/CMakeFiles/example_imagesegmentation.dir/build
.PHONY : example_imagesegmentation/fast

#=============================================================================
# Target rules for targets named example_permute

# Build rule for target.
example_permute: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example_permute
.PHONY : example_permute

# fast build rule for target.
example_permute/fast:
	$(MAKE) -f examples/CMakeFiles/example_permute.dir/build.make examples/CMakeFiles/example_permute.dir/build
.PHONY : example_permute/fast

#=============================================================================
# Target rules for targets named example_sprinkler

# Build rule for target.
example_sprinkler: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example_sprinkler
.PHONY : example_sprinkler

# fast build rule for target.
example_sprinkler/fast:
	$(MAKE) -f examples/CMakeFiles/example_sprinkler.dir/build.make examples/CMakeFiles/example_sprinkler.dir/build
.PHONY : example_sprinkler/fast

#=============================================================================
# Target rules for targets named example_sprinkler_em

# Build rule for target.
example_sprinkler_em: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example_sprinkler_em
.PHONY : example_sprinkler_em

# fast build rule for target.
example_sprinkler_em/fast:
	$(MAKE) -f examples/CMakeFiles/example_sprinkler_em.dir/build.make examples/CMakeFiles/example_sprinkler_em.dir/build
.PHONY : example_sprinkler_em/fast

#=============================================================================
# Target rules for targets named example_sprinkler_gibbs

# Build rule for target.
example_sprinkler_gibbs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example_sprinkler_gibbs
.PHONY : example_sprinkler_gibbs

# fast build rule for target.
example_sprinkler_gibbs/fast:
	$(MAKE) -f examples/CMakeFiles/example_sprinkler_gibbs.dir/build.make examples/CMakeFiles/example_sprinkler_gibbs.dir/build
.PHONY : example_sprinkler_gibbs/fast

#=============================================================================
# Target rules for targets named example_varset

# Build rule for target.
example_varset: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example_varset
.PHONY : example_varset

# fast build rule for target.
example_varset/fast:
	$(MAKE) -f examples/CMakeFiles/example_varset.dir/build.make examples/CMakeFiles/example_varset.dir/build
.PHONY : example_varset/fast

#=============================================================================
# Target rules for targets named uai2010-aie-solver

# Build rule for target.
uai2010-aie-solver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uai2010-aie-solver
.PHONY : uai2010-aie-solver

# fast build rule for target.
uai2010-aie-solver/fast:
	$(MAKE) -f examples/CMakeFiles/uai2010-aie-solver.dir/build.make examples/CMakeFiles/uai2010-aie-solver.dir/build
.PHONY : uai2010-aie-solver/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... dai"
	@echo "... testbbp"
	@echo "... testdai"
	@echo "... testem"
	@echo "... alldai_test"
	@echo "... bipgraph_test"
	@echo "... clustergraph_test"
	@echo "... dag_test"
	@echo "... daialg_test"
	@echo "... enum_test"
	@echo "... exceptions_test"
	@echo "... factor_test"
	@echo "... factorgraph_test"
	@echo "... graph_test"
	@echo "... index_test"
	@echo "... prob_test"
	@echo "... properties_test"
	@echo "... regiongraph_test"
	@echo "... smallset_test"
	@echo "... util_test"
	@echo "... var_test"
	@echo "... varset_test"
	@echo "... weightedgraph_test"
	@echo "... createfg"
	@echo "... fg2dot"
	@echo "... fginfo"
	@echo "... uai2fg"
	@echo "... example"
	@echo "... example_bipgraph"
	@echo "... example_imagesegmentation"
	@echo "... example_permute"
	@echo "... example_sprinkler"
	@echo "... example_sprinkler_em"
	@echo "... example_sprinkler_gibbs"
	@echo "... example_varset"
	@echo "... uai2010-aie-solver"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

